#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using PastebinMVC;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<PastebinMVC.Models.PasteModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"left\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Home\Index.cshtml"
     using (Html.BeginForm("Paste", "Home", FormMethod.Post, new { target = "_blank", id = "myDiv" }))
    {
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Home\Index.cshtml"
   Write(Html.TextArea("currentPaste", Model.CurrentPaste ?? string.Empty, new { @class = "border" }));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Home\Index.cshtml"
                                                                                                     
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Home\Index.cshtml"
   Write(Html.LabelFor(model => model.SyntaxFormatterCode, new { style = "font-family:verdana;font-size:small;color:##383c3a" }));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Home\Index.cshtml"
                                                                                                                                
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Index.cshtml"
   Write(Html.DropDownListFor(model => model.SyntaxFormatterCode, new SelectList(Model.SyntaxFormatters, "Value", "Text"), "-- None --"));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Index.cshtml"
                                                                                                                                        

            
            #line default
            #line hidden
WriteLiteral("        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" style=\"float:right\"");

WriteLiteral(">Save</button>\r\n");

            
            #line 14 "..\..\Views\Home\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Home\Index.cshtml"
     if (Request.IsAuthenticated)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" style=\"background-color:#d2e2f9; text-align:center; padding: 5px; font-size:smal" +
"l; font-family: Verdana; color:#757b79\"");

WriteLiteral(">\r\n            Previous pastes\r\n        </div>\r\n");

WriteLiteral("        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tr>\r\n                <th></th>\r\n                <th></th>\r\n      " +
"      </tr>\r\n");

            
            #line 28 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Home\Index.cshtml"
             foreach (var item in Model.PreviousPastes)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" width=\"70%\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\Home\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\Home\Index.cshtml"
                   Write(Html.ActionLink("Details", "Paste", new { pasteId = item.Id }, new { target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral(" | \r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Home\Index.cshtml"
                   Write(Html.ActionLink("Delete", "Delete", new { pasteId = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 39 "..\..\Views\Home\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n");

            
            #line 41 "..\..\Views\Home\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
